version: '3.7'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./backend/db.dev.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: ./backend
    command: python ./backend/manage.py runserver 0:8000
    env_file:
      - ./backend/db.dev.env
      - ./backend/web.dev.env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  celery:
    build: ./backend
    command: celery worker --app=core --loglevel=debug
    env_file:
      - ./backend/db.dev.env
      - ./backend/web.dev.env
    depends_on:
      - web
      - redis
  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  redis:
    image: redis:5-alpine
